top_srcdir   = /opt/httpd-2.2.23
top_builddir = /opt/httpd-2.2.23
srcdir       = /opt/httpd-2.2.23/modules/loggers
builddir     = /opt/httpd-2.2.23/modules/loggers
VPATH        = /opt/httpd-2.2.23/modules/loggers

include $(top_srcdir)/build/special.mk

