top_srcdir   = /opt/httpd-2.2.23
top_builddir = /opt/httpd-2.2.23
srcdir       = /opt/httpd-2.2.23/modules/metadata
builddir     = /opt/httpd-2.2.23/modules/metadata
VPATH        = /opt/httpd-2.2.23/modules/metadata

include $(top_srcdir)/build/special.mk

