top_srcdir   = /opt/httpd-2.2.23
top_builddir = /opt/httpd-2.2.23
srcdir       = /opt/httpd-2.2.23/modules
builddir     = /opt/httpd-2.2.23/modules
VPATH        = /opt/httpd-2.2.23/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

