top_srcdir   = /opt/httpd-2.2.23
top_builddir = /opt/httpd-2.2.23
srcdir       = /opt/httpd-2.2.23/os
builddir     = /opt/httpd-2.2.23/os
VPATH        = /opt/httpd-2.2.23/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
