top_srcdir   = /opt/httpd-2.2.23
top_builddir = /opt/httpd-2.2.23
srcdir       = /opt/httpd-2.2.23/modules/mappers
builddir     = /opt/httpd-2.2.23/modules/mappers
VPATH        = /opt/httpd-2.2.23/modules/mappers

include $(top_srcdir)/build/special.mk

