top_srcdir   = /opt/httpd-2.2.23
top_builddir = /opt/httpd-2.2.23
srcdir       = /opt/httpd-2.2.23/modules/echo
builddir     = /opt/httpd-2.2.23/modules/echo
VPATH        = /opt/httpd-2.2.23/modules/echo

include $(top_srcdir)/build/special.mk

