source PKG_ACTIVITY.sql
source PKG_AUDIT.sql
source PKG_BALANCE.sql
source PKG_CHECKBILL.sql
source PKG_ERATING_CHARGING.sql
source PKG_ERATING_PASSPORT.sql
source PKG_ERATING_TOOLKITS.sql
source PKG_ERATING_SALES.sql
source PKG_EXCHANGE.sql
source PKG_GATEWAY.sql
source PKG_GATEWAY_SETTING.sql
source PKG_GROUP.sql
source PKG_IB.sql
source PKG_INDULGENCE.sql
source PKG_ITEM.sql
source PKG_JOINT.sql
source PKG_LOG.sql
source PKG_OPTION.sql
source PKG_ROLE.sql
source PKG_STAT.sql
source PKG_USER.sql
source PKG_UTIL.sql
source PKG_UNITE.sql