top_srcdir   = /opt/httpd-2.2.23
top_builddir = /opt/httpd-2.2.23
srcdir       = /opt/httpd-2.2.23/server/mpm
builddir     = /opt/httpd-2.2.23/server/mpm
VPATH        = /opt/httpd-2.2.23/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
