top_srcdir   = /opt/httpd-2.2.23
top_builddir = /opt/httpd-2.2.23
srcdir       = /opt/httpd-2.2.23/modules/filters
builddir     = /opt/httpd-2.2.23/modules/filters
VPATH        = /opt/httpd-2.2.23/modules/filters

include $(top_srcdir)/build/special.mk

