top_srcdir   = /opt/httpd-2.2.23
top_builddir = /opt/httpd-2.2.23
srcdir       = /opt/httpd-2.2.23/modules/aaa
builddir     = /opt/httpd-2.2.23/modules/aaa
VPATH        = /opt/httpd-2.2.23/modules/aaa

include $(top_srcdir)/build/special.mk

