top_srcdir   = /opt/httpd-2.2.23
top_builddir = /opt/httpd-2.2.23
srcdir       = /opt/httpd-2.2.23/modules/http
builddir     = /opt/httpd-2.2.23/modules/http
VPATH        = /opt/httpd-2.2.23/modules/http

include $(top_srcdir)/build/special.mk

