top_srcdir   = /opt/httpd-2.2.23
top_builddir = /opt/httpd-2.2.23
srcdir       = /opt/httpd-2.2.23/modules/generators
builddir     = /opt/httpd-2.2.23/modules/generators
VPATH        = /opt/httpd-2.2.23/modules/generators

include $(top_srcdir)/build/special.mk

