top_srcdir   = /opt/httpd-2.2.23
top_builddir = /opt/httpd-2.2.23
srcdir       = /opt/httpd-2.2.23/modules/cache
builddir     = /opt/httpd-2.2.23/modules/cache
VPATH        = /opt/httpd-2.2.23/modules/cache

include $(top_srcdir)/build/special.mk

